# Generated by Django 5.1.4 on 2025-02-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_estimated_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='priority_price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5),
            preserve_default=False,
        ),
    ]
