# Generated by Django 5.1.4 on 2025-02-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_priority_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='priority_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
