# Generated by Django 5.1.4 on 2025-02-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_priority_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
